making a slight change to restart the main bot as it is no longer writing to the log channel on the discord server.
I suspect but am not entirely sure that this is because of some past issues with the discord uptime.  
  
I did some investigation and the last error that was printed before the connection to the bot_log channel was lost was   
  
2018-10-05 18:59:18 = WARNING - Error in data transfer
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "/usr/local/lib/python3.5/site-packages/websockets/framing.py", line 100, in read
    data = yield from reader(2)
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 668, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 458, in _wait_for_data
    yield from self._waiter
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
2018-10-05 18:59:24 = WARNING - Task exception was never retrieved
future: <Task finished coro=<write_to_bot_log_channel() done, defined at ./main.py:103> exception=ClientOSError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 242, in _step
    result = coro.throw(exc)
  File "./main.py", line 132, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.5/site-packages/discord/abc.py", line 764, in send
    data = yield from state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/usr/local/lib/python3.5/site-packages/discord/http.py", line 156, in request
    r = yield from self._session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/aiohttp/helpers.py", line 97, in __iter__
    ret = yield from self._coro
  File "/usr/local/lib/python3.5/site-packages/aiohttp/client.py", line 241, in _request
    yield from resp.start(conn, read_until_eof)
  File "/usr/local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 559, in start
    (message, payload) = yield from self._protocol.read()
  File "/usr/local/lib/python3.5/site-packages/aiohttp/streams.py", line 509, in read
    yield from self._waiter
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

After doing some googling regarding issue `exception=ClientOSError(104, 'Connection reset by peer')>`, I came across an SO page that had this answer https://stackoverflow.com/a/20568874 . This makes me suspect that it was something cause by a hiccup with the discord server and nothing buggy with our actual code.